name: Makefile CI

on:
  push:
    branches: [ ci ]
  pull_request:
    branches: [ ci ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install package
      run:  apt-get -y install bison  flex gcc build-essential make
      
    - name: Make
      run: make
