name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: install
      run:  apt-get install bison  flex gcc build-essential
      
    - name: Install dependencies
      run: make
