name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install package
      run:  sudo apt-get -y install bison  flex gcc build-essential make
      
    - name: Make
      run: make
